BanWaves:
                                          StoredTime: 0 # DO NOT TOUCH THIS
                                          Time: 86400000 #in miliseconds(Ban wave will occur every x hour,days,seconds etc;)
                                          Message: '&aA ban wave has been executed {total} players have been banned'
                                          BanWaveNoBans: '&aThere have been no bans within the last 24 hours'
                                          EnableBanWave: true #when disabled all users in the pendingusers.yml will be removed.
                                          EraseBansOnDisable: true #should the bans be erased on the /banwave off command
                                          CommandOnBanWave:
                                           - ban {name} {reason}  # {name} name of the person {reason} why they were banned.  {name}, {uuid}, {reason}
                                          TotalBans: 0
                                          CommandsMessages:
                                            BanWaveAddCommand: '&a{name} &chas been added to the ban wave. They will be banned in the next wave.'
                                            BanWaveExecuteCommand: '&aBanwave is starting.'
                                            BanWaveRemoveCommand: '&c{name} has been removed from the ban wave.'
                                            BanWaveOffCommand: '&cBanwave disabled. All players on the list will no longer be banned.'
                                            BanWaveOnCommand: '&cBanwave enabled.'